baseURL = "https://dn42.routedbits.com/"
languageCode = "en-us"
title = "RoutedBits"
# enableRobotsTXT = true

theme = "compose"
enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

#  menu items
[[menu.main]]
    name = "Docs"
    weight = 2
    url = "docs/"

[[menu.main]]
    name = "Looking Glass"
    weight = 3
    url = "https://lg.routedbits.com"

[[menu.main]]
    name = "Grafana"
    weight = 4
    url = "https://grafana.routedbits.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "monokai"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

# Everything below this are Site Params

[params]
  author = "RoutedBits"
  searchPlaceholder = "Search the docs ..."
  repo = "https://github.com/routedbits/routedbits.github.io"
  time_format_blog = "Monday, January 02, 2006"
  time_format_default = "January 2, 2006"
  enableDarkMode = true # set to false to disable darkmode by default

  [params.logo]
    lightMode = "compose.svg"
    darkMode = "compose-light.svg"

  [params.source]
    name = "GitHub"
    icon = "github.svg"
    url = "https://github.com/routedbits"
